import { writeTextFile } from '@tauri-apps/plugin-fs';
import { dbProvider } from './db';
import { join } from '@tauri-apps/api/path';

export class ViewSyncService {
  /**
   * Reads all artefacts for a given task and writes them as read-only Markdown files
   * to the configured workspace path.
   */
  static async syncArtefactsToWorkspace(taskId: string, workspaceRoot: string) {
    const db = await dbProvider.getDb();
    
    // Fetch artefacts
    const artefacts = await db.select<Array<{ type: string; content: string }>>(
      `SELECT type, content FROM artefacts WHERE task_id = $1`,
      [taskId]
    );

    for (const artefact of artefacts) {
      let filename = 'Unknown.md';
      switch (artefact.type) {
        case 'PRD': filename = 'PRD.md'; break;
        case 'ARCHITECTURE': filename = 'Architecture.md'; break;
        case 'TEST_PLAN': filename = 'TestPlan.md'; break;
        default: filename = `${artefact.type}.md`;
      }

      const filepath = await join(workspaceRoot, filename);
      
      const header = `<!-- 
  READ-ONLY VIEW
  This file is automatically generated from the BMad State DB.
  DO NOT EDIT manually. AI agents should update the DB state instead.
-->

`;
      
      const fullContent = header + artefact.content;
      
      try {
        await writeTextFile(filepath, fullContent);
        console.log(`Successfully synced ${filename} to ${workspaceRoot}`);
      } catch (err) {
        console.error('Failed to write artefact view:', err);
      }
    }
  }

  /**
   * Save an artefact to the DB and immediately trigger a sync
   */
  static async updateArtefact(taskId: string, type: string, content: string, workspaceRoot: string) {
    const db = await dbProvider.getDb();
    
    // Check if exists
    const existing = await db.select<Array<{ id: string }>>(
      `SELECT id FROM artefacts WHERE task_id = $1 AND type = $2`,
      [taskId, type]
    );

    if (existing.length > 0) {
      await db.execute(
        `UPDATE artefacts SET content = $1, updated_at = CURRENT_TIMESTAMP WHERE id = $2`,
        [content, existing[0].id]
      );
    } else {
      await db.execute(
        `INSERT INTO artefacts (id, task_id, type, content) VALUES ($1, $2, $3, $4)`,
        [crypto.randomUUID(), taskId, type, content]
      );
    }

    // Sync views
    await this.syncArtefactsToWorkspace(taskId, workspaceRoot);
  }
}
